FROM mcr.microsoft.com/appsvc/node:10-lts
# FROM node:16.7.0

LABEL version="1.0"
LABEL description="This is the base docker image for the Venus application frontend"

WORKDIR /app

COPY ["package.json", "package-lock.json", "./"]

COPY . .

RUN npm install --production

RUN npm run build

# EXPOSE 3000

# CMD ["npm", "start"]

# CMD ["npm", "run"]

ENV HOST 0.0.0.0
ENV PORT 8080
EXPOSE 8080

ENTRYPOINT ["pm2", "start", "--no-daemon", "/opt/startup/default-static-site.js"]
